export const projects = [
  {
    title: 'Holiday Destinations',
    description: "The app is a place, where its community members can add and vote on holiday destinations across Bulgaria.",
      image: '/images/holiday-destinations.png',
      tags: ['React.js', 'JSX', 'CSS', 'Firebase', 'Headless CMS'],
    source: 'https://github.com/k-vassilev/react-holiday-catalog',
    visit: 'https://react-holiday-catalog.web.app/',
    id: 0,
  },
  {
    title: 'Realtor NextJs',
    description: "An app for browsing real-estate properties to buy or to rent. The app is fething data from an external API - rapidapi.com",
      image: '/images/realtor.png',
      tags: ['React.js', 'Next.js', 'chakra-ui', 'nprogress'],
    source: 'https://github.com/k-vassilev/realtor-nextjs',
    visit: 'https://realtor-nextjs.vercel.app/',
    id: 1,
  },
  {
    title: 'Covid-19 Tracker',
    description: "A React app for tracking Covid-19 cases and statistics globally, using external API",
    image: '/images/covid19.png',
    tags: ['React.js', 'Firebase', 'chart.js', 'material-ui'],
    source: 'https://github.com/k-vassilev/react-covid-19-tracker',
    visit: 'https://covid-19-tracker-a2f6e.web.app/',
    id: 2,
  },
  {
    title: 'React Chat App',
    description: "A simple React chat application, which can be used to communicate with other registered users live.",
    image: '/images/chat-app.png',
    tags: ['React.js', 'Netlify', 'react-chat-engine', 'axios'],
    source: 'https://github.com/k-vassilev/react-kv-chat',
    visit: 'https://kv-chat-app.netlify.app/',
    id: 3,
  },
  {
    title: 'Portfolio Landing Page',
    description: "A portfolio react SPA to showcase additional projects, skillsets, CV and contacts",
    image: '/images/portfolio.png',
    tags: ['React.js', 'Next.js', 'Firebase', 'styled-components'],
    source: 'https://github.com/k-vassilev/kristian_vassilev_portfolio',
    visit: 'https://kristianvassilev.com/',
    id: 4,
  },
  {
    title: 'Calculator',
    description:"A simple React.js calculator for playing around with useState, useEffect, events and a deployment in Firebase.",
    image: '/images/calc.png',
    tags: ['React', 'JavaScript', 'CSS'],
    source: 'https://github.com/k-vassilev/react-calculator',
    visit: 'https://react-calculator-efb89.web.app/',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2012, text: 'Started working at Ballisticcell as a ERP expert', },
  { year: 2016, text: 'Founded Ephedra-TK web agency', },
  { year: 2021, text: 'Started working in DevriX as Web Developer', },
];